apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespace }}
  name: {{ .Values.Name }}
spec:
  type: {{ .Values.Servicetype }}
  selector:
    app: {{ .Values.Name }}
  ports:
    - protocol: TCP
      name: {{ .Values.Ports.name }}
      port: {{ .Values.Ports.containerPort }}
      targetPort: {{ .Values.Ports.containerPort }}
      nodePort: {{ .Values.Ports.nodePort }}
