# This is a basic workflow to help you get started with Actions

name: simapi-k8s-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the <BRANCH>
  push:
    branches: [ lablab ]
  pull_request:
    branches: [ lablab ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Prepare:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: |
          echo ">>>>> LIST FILES CURRENT DIR" 
          ls -lta
          echo ">>>> WORKSPACE DIR "
          pwd

  Build:
    needs: Prepare
    runs-on: self-hosted
    steps:
      - name: build
        run: sudo docker build -t 952561415/simapi:1.0.0 .
      - name: push
        run: sudo docker push 952561415/simapi:1.0.0

  Deploy:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: deploy
        run: helm upgrade --install -n test-environment simapi helm/simapi/ -f helm/simapi/values.yaml

  Test:
    needs: Deploy
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo "CHECK : " $(curl 10.10.10.91:31000)
          echo "HEALTH : " $(curl 10.10.10.91:31000/health)
