# This is a basic workflow to help you get started with Actions

name: simapi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the <BRANCH>
  push:
    branches: [ lablab ]
  pull_request:
    branches: [ lablab ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Prepare:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: check
        run: |
          echo ">>>>> LIST FILES CURRENT DIR" 
          ls -lta
          echo ">>>> WORKSPACE DIR "
          pwd

  Build:
    needs: Prepare
    runs-on: self-hosted
    steps:
      - name: build
        run: docker build -t simapi:1.0.0 .

  Deploy:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: armed
        run: |
          if [ ! -z "$(docker ps -a | grep simapi)" ];then
            docker ps -a | grep simapi | awk '{print $1}' | xargs docker rm -f
          else
            echo "NOT FOUND ANY CONTAINER READY TO DRPLOY"
          fi

      - name: deploy
        run: docker run --name simapi -p 80:3100 -d simapi:1.0.0

  Test:
    needs: Deploy
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo "CHECK : " $(curl 127.0.0.1)
          echo "HEALTH : " $(curl 127.0.0.1/health)
